const defaults = { name: 'Nova Reyes', initial: 'N', level: 4, xp: 850, total: 18.4, week: 7.2, runs: 14, badges: 7, color: 'coral', motion: true, audio: true, claimed: [], progress: { dawn: 2, stride: 3.1, night: 0, weekly: 7.2, season: 18.4, legend: 6 } };
let state = JSON.parse(localStorage.getItem('stride-state') || 'null') || defaults;
let running = false, paused = false, runDistance = 0, runTimer, currentRoute = { name: 'Nightshift Loop', distance: 4.8, xp: 120 };
const $ = id => document.getElementById(id);
const missions = [
  { id:'dawn', type:'daily', icon:'◒', name:'Find first light', desc:'Complete 3 runs before 09:00', goal:3, reward:40 },
  { id:'stride', type:'daily', icon:'↗', name:'Hold your stride', desc:'Run 5 km at any pace', goal:5, reward:60 },
  { id:'night', type:'daily', icon:'☾', name:'After dark', desc:'Finish a Nightshift route', goal:1, reward:80 },
  { id:'weekly', type:'weekly', icon:'⌁', name:'City in motion', desc:'Cover 15 km this week', goal:15, reward:160 },
  { id:'season', type:'season', icon:'✦', name:'Mapmaker I', desc:'Run 40 km during Neon Season', goal:40, reward:300 },
  { id:'legend', type:'legend', icon:'♜', name:'The Long Way Home', desc:'Complete 12 distinct routes', goal:12, reward:600 }
];
const routes = [
  {name:'Nightshift Loop',distance:4.8,xp:120,desc:'Neon pavement & quick corners',tag:'RECOMMENDED'},
  {name:'Harbor Static',distance:7.2,xp:185,desc:'Wind, water, nowhere to hide',tag:'INTERMEDIATE'},
  {name:'Glassline Rise',distance:10,xp:270,desc:'Vertical city. Vertical mind.',tag:'HARD'}
];
const badges = [['☾','Night Cartographer',true],['↗','First Step',true],['⌁','Concrete Lungs',true],['✦','Eclipse Chaser',true],['⚡','Six Alive',true],['◉','Fast Company',true],['♜','Long Road',true],['◇','Skyline',false],['☀','Sun Chaser',false],['♧','Trail Ghost',false],['♢','Perfect Pace',false],['☁','Stormproof',false]];
const tips = ['Tap <b>Space</b> mid-run to surge and earn a small XP bonus.', 'Level 5 unlocks <b>Runner Notes</b>, a place to keep route memories.', 'Weekly missions stack with daily missions. Make one run count twice.', 'Commands are live: try <b>/run</b>, <b>/missions</b>, or <b>/help</b>.'];

function save(){ localStorage.setItem('stride-state', JSON.stringify(state)); }
function setTheme(){ document.documentElement.style.setProperty('--accent', {coral:'#ff654f',mint:'#6ddbb1',violet:'#a486f5',gold:'#f7bd57'}[state.color]); document.body.classList.toggle('reduce-motion', !state.motion); }
function render(){
  setTheme(); const first = state.name.split(' ')[0];
  $('railName').textContent = first; $('railAvatar').textContent = state.initial; $('profileAvatar').textContent = state.initial; $('profileName').textContent = state.name;
  ['level','railLevel'].forEach(id => $(id).textContent = state.level); $('totalDistance').innerHTML = `${state.total.toFixed(1)} <b>km</b>`; $('weekDistance').innerHTML = `${state.week.toFixed(1)} <b>km</b>`; $('profileRuns').textContent = state.runs; $('profileXp').textContent = state.xp; $('badgeCount').innerHTML = `${state.badges} <small>/ 24</small>`;
  const notes = state.level >= 5; $('notesText').textContent = notes ? 'Route journal ready' : 'Unlocks at level 5'; $('notesLock').textContent = notes ? '✎' : '🔒'; document.querySelector('.notes-card').classList.toggle('unlocked',notes);
  $('motionToggle').checked=state.motion; $('audioToggle').checked=state.audio; document.querySelectorAll('.swatch').forEach(x=>x.classList.toggle('selected',x.dataset.color===state.color));
  renderMini(); renderRoutes(); renderMissions(document.querySelector('.filter.active')?.dataset.filter || 'daily'); renderVault(); save();
}
function progress(m){ return Math.min(state.progress[m.id] || 0, m.goal); }
function renderMini(){ $('miniMissions').innerHTML = missions.slice(0,3).map(m=>`<article class="mini-card"><header><span>${m.type.toUpperCase()}</span><span>+${m.reward} XP</span></header><h4>${m.name}</h4><div class="progress"><div style="width:${progress(m)/m.goal*100}%"></div></div><span>${progress(m).toFixed(progress(m)%1?1:0)} / ${m.goal} ${m.id==='stride'?'km':'runs'}</span></article>`).join(''); }
function renderRoutes(){ $('routeGrid').innerHTML=routes.map((r,i)=>`<article class="route-card" data-route="${i}"><p class="eyebrow">${r.tag}</p><h3>${r.name}</h3><p>${r.desc}</p><div class="route-meta"><span>${r.distance.toFixed(1)} KM</span><span>+${r.xp} XP</span><span>START →</span></div></article>`).join(''); document.querySelectorAll('.route-card').forEach(el=>el.onclick=()=>startRun(routes[el.dataset.route])); }
function renderMissions(type){ const list=missions.filter(m=>m.type===type); $('missionList').innerHTML=list.map(m=>{let done=progress(m)>=m.goal, claimed=state.claimed.includes(m.id);return `<article class="mission-card"><div class="mission-symbol">${m.icon}</div><div><h4>${m.name}</h4><p>${m.desc}</p></div><div class="mission-progress"><strong>${progress(m).toFixed(progress(m)%1?1:0)} / ${m.goal}${['stride','weekly','season'].includes(m.id)?' km':''}</strong><div class="progress"><div style="width:${progress(m)/m.goal*100}%"></div></div></div><button class="claim" data-claim="${m.id}" ${!done||claimed?'disabled':''}>${claimed?'CLAIMED':done?'CLAIM XP':`+${m.reward} XP`}</button></article>`}).join(''); document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>claim(b.dataset.claim)); }
function renderVault(){ $('badgeGrid').innerHTML=badges.map(x=>`<div class="badge ${x[2]?'':'locked'}"><div class="badge-icon">${x[0]}</div><b>${x[1]}</b><small>${x[2]?'EARNED':'LOCKED'}</small></div>`).join(''); $('achievementList').innerHTML=[['⚡','Seven-day signal','Run on seven consecutive days'],['◒','Daybreaker','Complete an early run'],['▤','Field notes','Reach runner level 5']].map((a,i)=>`<div class="achievement"><span>${a[0]}</span><div><b>${a[1]}</b><small>${a[2]}</small></div></div>`).join(''); }
function claim(id){const m=missions.find(x=>x.id===id); state.claimed.push(id); state.xp+=m.reward; levelUp(); toast(`+${m.reward} XP banked`); render();}
function levelUp(){const next=state.level*300;if(state.xp>=next){state.level++;toast(`LEVEL ${state.level} UNLOCKED`); if(state.level===5) toast('RUNNER NOTES UNLOCKED');}}
function startRun(route=currentRoute){currentRoute=route; runDistance=0; running=true;paused=false;$('gameOverlay').classList.remove('hidden');$('runRouteName').textContent=route.name.toUpperCase();$('runGoal').textContent=`0.00 / ${route.distance.toFixed(2)} KM`; tick();}
function tick(){clearInterval(runTimer);runTimer=setInterval(()=>{if(paused)return;runDistance=Math.min(currentRoute.distance,runDistance+.04);$('runDistance').innerHTML=`${runDistance.toFixed(2)} <i>KM</i>`;$('runGoal').textContent=`${runDistance.toFixed(2)} / ${currentRoute.distance.toFixed(2)} KM`;$('runProgress').style.width=`${runDistance/currentRoute.distance*100}%`; if(runDistance>=currentRoute.distance) finishRun();},1000);}
function pauseRun(reason=''){if(!running)return;paused=true;$('pausePanel').classList.remove('hidden'); if(reason) $('pausePanel').querySelector('h2').textContent='Run paused while you were away.';}
function resumeRun(){paused=false;$('pausePanel').classList.add('hidden');}
function finishRun(){clearInterval(runTimer);running=false;$('gameOverlay').classList.add('hidden');state.total+=runDistance;state.week+=runDistance;state.runs++;state.xp+=Math.round(currentRoute.xp*runDistance/currentRoute.distance);state.progress.stride=(state.progress.stride||0)+runDistance;state.progress.weekly=(state.progress.weekly||0)+runDistance;state.progress.season=(state.progress.season||0)+runDistance;if(currentRoute.name==='Nightshift Loop')state.progress.night=1;levelUp();render();toast(`RUN COMPLETE · +${currentRoute.xp} XP`);}
function quitRun(){clearInterval(runTimer);running=false;$('gameOverlay').classList.add('hidden');toast('Run saved as a draft');}
function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600);}
function showTab(tab){document.querySelectorAll('.tab-page').forEach(x=>x.classList.toggle('hidden',x.id!==tab));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));$('pageTitle').textContent=tab==='home'?`Good evening, ${state.name.split(' ')[0]}.`:({routes:'Choose a new line.',missions:'Your city is calling.',vault:'Everything leaves a trace.',profile:'This is your run.',settings:'Tune your experience.'}[tab]);$('headerKicker').textContent=tab==='home'?"THE RUNNER'S HOME":tab.toUpperCase();}
function showTip(){let i=0; const tickTip=()=>{$('tipText').innerHTML=tips[i++%tips.length];$('tip').classList.remove('hidden');setTimeout(()=>$('tip').classList.add('hidden'),5000)};setTimeout(tickTip,5000);setInterval(tickTip,18000);}
function command(){const val=prompt('Runner command');if(!val)return;const cmd=val.trim().toLowerCase();if(cmd==='/run')startRun();else if(cmd==='/missions')showTab('missions');else if(cmd==='/help')toast('Commands: /run · /missions · /home');else if(cmd==='/home')showTab('home');else toast('Unknown command. Try /help');}

$('enter').onclick=()=>{$('intro').classList.add('hidden');$('app').classList.remove('hidden');showTip();};document.addEventListener('keydown',e=>{if($('intro').classList.contains('hidden')===false&&e.key==='Enter')$('enter').click();if(e.key==='/'&&!running){e.preventDefault();command();}if(e.code==='Space'&&running&&!paused){state.xp+=5;$('xpFloat').textContent='+5 XP SURGE';}if(e.key==='Escape'&&running)pauseRun();});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-tab-go]').forEach(b=>b.onclick=()=>showTab(b.dataset.tabGo));$('runButton').onclick=()=>startRun();$('pauseRun').onclick=()=>pauseRun();$('resumeRun').onclick=resumeRun;$('quitRun').onclick=quitRun;$('endRun').onclick=finishRun;window.addEventListener('blur',()=>pauseRun('away'));$('closeTip').onclick=()=>$('tip').classList.add('hidden');
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMissions(b.dataset.filter);});$('avatarButton').onclick=()=>{const x=prompt('Choose one letter or initial',state.initial);if(x){state.initial=x[0].toUpperCase();render();}};$('editName').onclick=()=>{const x=prompt('Your runner name',state.name);if(x){state.name=x.trim();render();}};document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{state.color=b.dataset.color;render();});$('motionToggle').onchange=e=>{state.motion=e.target.checked;render()};$('audioToggle').onchange=e=>{state.audio=e.target.checked;render()};$('soundBtn').onclick=()=>{state.audio=!state.audio;render();toast(state.audio?'Audio enabled':'Audio muted')};$('resetGame').onclick=()=>{if(confirm('Reset all local runner progress?')){state=structuredClone(defaults);render();toast('Fresh route. Fresh start.')}};
render();
