const updates=[
 {version:'UPDATE 18',date:'21 AUG 2026',title:'CINEMATIC SPLASH',text:'Added a cinematic splash sequence to strengthen the game opening and presentation.'},
 {version:'UPDATE 17',date:'20 AUG 2026',title:'CINEMATIC & TUTORIAL PACING',text:'Improved cinematic arrival timing and refined the tutorial quick-start flow for clearer onboarding.'},
 {version:'UPDATE 15',date:'19 AUG 2026',title:'ADAPTIVE MISSIONS',text:'Expanded mission behaviour with adaptive systems and stronger progression between runs.'},
 {version:'UPDATE 14',date:'19 AUG 2026',title:'ENCOUNTER EVENTS',text:'Added dynamic encounter events to create more reactive and varied gameplay situations.'},
 {version:'UPDATE 12',date:'18 AUG 2026',title:'MISSION FLOW',text:'Improved mission flow, finish handling and recovery paths to keep runs stable and readable.'},
 {version:'UPDATE 11',date:'18 AUG 2026',title:'DYNAMIC WORLD',text:'Expanded dynamic world mechanics and environmental responses around the player.'},
 {version:'UPDATE 10',date:'17 AUG 2026',title:'GAME FEEL & HUD',text:'Improved gameplay feedback, HUD presentation and moment-to-moment visual clarity.'},
 {version:'UPDATE 09',date:'17 AUG 2026',title:'WORLD INTERACTION',text:'Added and refined world interaction systems for a more reactive delivery experience.'}
];
const block=e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.()};
function create(){if(document.getElementById('relayUpdatesModal'))return document.getElementById('relayUpdatesModal');const modal=document.createElement('section');modal.id='relayUpdatesModal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','relayUpdatesHeading');modal.innerHTML=`<div class="relay-updates-card"><header class="relay-updates-head"><div><p class="relay-updates-kicker">RELAY RUNNER // VERSION HISTORY</p><h2 id="relayUpdatesHeading">GAME UPDATES</h2></div><button type="button" class="relay-updates-close" aria-label="Close updates">×</button></header><div class="relay-updates-list">${updates.map(u=>`<article class="relay-update-row"><div class="relay-update-meta"><span class="relay-update-version">${u.version}</span><time class="relay-update-date">${u.date}</time></div><div class="relay-update-copy"><h3>${u.title}</h3><p>${u.text}</p></div></article>`).join('')}</div></div>`;for(const type of ['pointerdown','pointerup','mousedown','mouseup','touchstart','touchend','click'])modal.addEventListener(type,block,true);modal.querySelector('.relay-updates-card').addEventListener('click',e=>e.stopPropagation());modal.querySelector('.relay-updates-close').addEventListener('click',()=>close());modal.addEventListener('click',()=>close());document.body.append(modal);return modal}
function open(){const modal=create();modal.classList.add('is-open');document.body.style.overflow='hidden';modal.querySelector('.relay-updates-close').focus()}
function close(){const modal=document.getElementById('relayUpdatesModal');if(!modal)return;modal.classList.remove('is-open');document.body.style.overflow=''}
function bind(){const button=document.querySelector('[data-relay-updates]');if(!button)return;for(const type of ['pointerdown','pointerup','mousedown','mouseup','touchstart','touchend'])button.addEventListener(type,block,true);button.addEventListener('click',e=>{block(e);open()},true);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
