// Deterministic gameplay feature installer.
import { RunnerScene } from './scenes/RunnerScene.js';
import { installMissionFeatureGating } from './systems/mission-feature-gating-v1.js';
import { installEnemyRuntime } from './systems/enemy-runtime-v2.js';
import { installEnemyLayout } from './systems/enemy-layout-v2.js';
import { installEnemyAIAwareness } from './systems/enemy-ai-awareness-v1.js';
import { installGhostRun } from './systems/ghost-run-v1.js';
import { installReactiveCourierEncounter } from './systems/reactive-courier-encounter-v1.js';
import { installWorldMemory } from './systems/world-memory-v1.js';
import { installGrappleTraversal } from './systems/grapple-traversal-v1.js';
import { installTeleportNetwork } from './systems/teleport-network-v1.js';
import { installBiohazardContamination } from './systems/biohazard-contamination-v1.js';
import { installAutonomousCharacter } from './systems/autonomous-character-v1.js';
import { installPlayerVisualV2 } from './systems/player-visual-v2.js';
import { installCharacterStateReactions } from './systems/character-state-reactions-v1.js';
import { installEnemyDiscovery } from './systems/enemy-discovery-v1.js';
import { installEnemyDialogue } from './systems/enemy-dialogue-v1.js';
import { installEnemyProgression } from './systems/enemy-progression-v1.js';
import { installPuzzleEngine } from './systems/puzzle-engine-v1.js';
import { installPuzzleProgression } from './systems/puzzle-progression-v1.js';
import { installLockedZones } from './systems/locked-zones-v1.js';
import { installLockedGate } from './systems/locked-gate-v1.js';
import { installWorldProgression } from './systems/world-progression-v1.js';
import { installEnemyPuzzleIntegration } from './systems/enemy-puzzle-integration-v1.js';
import { installMissionProgressionPolish } from './systems/mission-progression-polish-v1.js';
import { installFireWater } from './systems/fire-water-v1.js';
import { installPowerFailure } from './systems/power-failure-v1.js';
import { installEarthquakeEvents } from './systems/earthquake-events-v1.js';
import { installEarthquakeCinematic } from './systems/earthquake-events-cinematic-v1.js';
import { installDroneStrikeRecovery } from './systems/drone-strike-recovery-v1.js';
import { installWaterSurvival } from './systems/water-survival-v1.js';
import { installForwardCollapseZone } from './systems/forward-collapse-zone-v1.js';

if (!RunnerScene.prototype.__relayFeatureRuntimeInstalled) {
  RunnerScene.prototype.__relayFeatureRuntimeInstalled = true;
  installMissionFeatureGating(RunnerScene);
  installEnemyLayout(RunnerScene);
  installEnemyRuntime(RunnerScene);
  installEnemyAIAwareness(RunnerScene);
  installGhostRun(RunnerScene);
  installWorldMemory(RunnerScene);
  installReactiveCourierEncounter(RunnerScene);
  installGrappleTraversal(RunnerScene);
  installTeleportNetwork(RunnerScene);
  installBiohazardContamination(RunnerScene);
  installAutonomousCharacter(RunnerScene);
  installPlayerVisualV2(RunnerScene);
  installCharacterStateReactions(RunnerScene);
  installEnemyDiscovery(RunnerScene);
  installEnemyDialogue(RunnerScene);
  installEnemyProgression(RunnerScene);
  installPuzzleEngine(RunnerScene);
  installPuzzleProgression(RunnerScene);
  installLockedZones(RunnerScene);
  installLockedGate(RunnerScene);
  installWorldProgression(RunnerScene);
  installEnemyPuzzleIntegration(RunnerScene);
  installMissionProgressionPolish(RunnerScene);
  installFireWater(RunnerScene);
  installPowerFailure(RunnerScene);
  installEarthquakeEvents(RunnerScene);
  installEarthquakeCinematic(RunnerScene);
  installDroneStrikeRecovery(RunnerScene);
  installWaterSurvival(RunnerScene);
  installForwardCollapseZone(RunnerScene);
}
