const LANG_KEY = 'relay-runner-language';
const LANGUAGES = { en: 'English', exyu: 'EX-YU', es: 'Español', de: 'Deutsch' };
const T = {
  en:{'FAQ':'FAQ','LATEST UPDATE':'LATEST UPDATE','OPTIONS':'OPTIONS','SETTINGS & CONTROLS':'SETTINGS & CONTROLS','EXIT':'EXIT','CLOSE SESSION':'CLOSE SESSION','PLAY NOW':'PLAY NOW','CONTINUE':'CONTINUE','PRESS ENTER TO BEGIN':'PRESS ENTER TO BEGIN','A ROOFTOP DELIVERY GAME':'A ROOFTOP DELIVERY GAME','OLD QUARTER':'OLD QUARTER','ROOFTOP RELAY':'ROOFTOP RELAY','SIGNALS':'SIGNALS','ROTATE SCREEN':'ROTATE SCREEN','Landscape gives the clearest view and full controls.':'Landscape gives the clearest view and full controls.','RESUME':'RESUME','MISSIONS':'MISSIONS','PROGRESS':'PROGRESS','SETTINGS':'SETTINGS','COURIER TERMINAL':'COURIER TERMINAL','KEEP THE':'KEEP THE','LINE OPEN.':'LINE OPEN.','RESTART BRIEFING':'RESTART BRIEFING','ESC CLOSE':'ESC CLOSE','GAMEPLAY / GUIDANCE':'GAMEPLAY / GUIDANCE','VOICE & AUDIO':'VOICE & AUDIO','DISPLAY':'DISPLAY','LANGUAGE':'LANGUAGE','TUTORIAL':'TUTORIAL','GAME AUDIO':'GAME AUDIO','SCREEN SHAKE':'SCREEN SHAKE','REDUCED MOTION':'REDUCED MOTION','ATMOSPHERIC RAIN':'ATMOSPHERIC RAIN','AI VOICE':'AI VOICE','MUSIC':'MUSIC','SFX':'SFX','GAME LANGUAGE':'GAME LANGUAGE','Choose your interface language':'Choose your interface language','FULLSCREEN':'FULLSCREEN','RESET OPTIONS':'RESET OPTIONS','CONTROLS':'CONTROLS','DELIVERY COMPLETE':'DELIVERY COMPLETE','LINE':'LINE','RESTORED.':'RESTORED.','NEXT RUN':'NEXT RUN','NEXT MISSION':'NEXT MISSION','RETURN TO BRIEFING':'RETURN TO BRIEFING','SIGNAL LOST':'SIGNAL LOST','RUN':'RUN','INTERRUPTED.':'INTERRUPTED.','TRY AGAIN':'TRY AGAIN','RANK UP':'RANK UP','ABILITY UNLOCKED':'ABILITY UNLOCKED','SESSION CLOSED':'SESSION CLOSED','SEE YOU':'SEE YOU','SOON.':'SOON.','RUNNING':'RUNNING','JUMP':'JUMP','SWORD':'SWORD','DASH':'DASH','BUILD':'BUILD','GEAR':'GEAR'},
  exyu:{'FAQ':'ČESTA PITANJA','LATEST UPDATE':'NAJNOVIJI UPDATE','OPTIONS':'OPCIJE','SETTINGS & CONTROLS':'POSTAVKE I KONTROLE','EXIT':'IZLAZ','CLOSE SESSION':'ZATVORI SESIJU','PLAY NOW':'IGRAJ','CONTINUE':'NASTAVI','PRESS ENTER TO BEGIN':'PRITISNI ENTER ZA POČETAK','A ROOFTOP DELIVERY GAME':'IGRA DOSTAVE PREKO KROVOVA','OLD QUARTER':'STARA ČETVRT','ROOFTOP RELAY':'KROVNA DOSTAVA','SIGNALS':'SIGNALI','ROTATE SCREEN':'OKRENI EKRAN','Landscape gives the clearest view and full controls.':'Vodoravni prikaz daje najbolji pogled i pune kontrole.','RESUME':'NASTAVI','MISSIONS':'MISIJE','PROGRESS':'NAPREDAK','SETTINGS':'POSTAVKE','COURIER TERMINAL':'KURIROV TERMINAL','KEEP THE':'ODRŽI','LINE OPEN.':'LINIJU OTVORENOM.','RESTART BRIEFING':'PONOVI UVOD','ESC CLOSE':'ESC ZATVORI','GAMEPLAY / GUIDANCE':'IGRA / UPUTE','VOICE & AUDIO':'GLAS I ZVUK','DISPLAY':'PRIKAZ','LANGUAGE':'JEZIK','TUTORIAL':'TUTORIJAL','GAME AUDIO':'ZVUK IGRE','SCREEN SHAKE':'TRESENJE KAMERE','REDUCED MOTION':'SMANJENO KRETANJE','ATMOSPHERIC RAIN':'ATMOSFERSKA KIŠA','AI VOICE':'AI GLAS','MUSIC':'MUZIKA','SFX':'ZVUČNI EFEKTI','GAME LANGUAGE':'JEZIK IGRE','Choose your interface language':'Izaberi jezik interfejsa','FULLSCREEN':'CIJELI EKRAN','RESET OPTIONS':'VRATI POSTAVKE','CONTROLS':'KONTROLE','DELIVERY COMPLETE':'DOSTAVA ZAVRŠENA','LINE':'LINIJA','RESTORED.':'OBNOVLJENA.','NEXT RUN':'SLJEDEĆA RUNDA','NEXT MISSION':'SLJEDEĆA MISIJA','RETURN TO BRIEFING':'NAZAD NA POČETAK','SIGNAL LOST':'SIGNAL IZGUBLJEN','RUN':'TRČANJE','INTERRUPTED.':'PREKINUT.','TRY AGAIN':'POKUŠAJ PONOVO','RANK UP':'NOVI RANG','ABILITY UNLOCKED':'OTKLJUČANA SPOSOBNOST','SESSION CLOSED':'SESIJA ZATVORENA','SEE YOU':'VIDIMO','SOON.':'SE USKORO.','RUNNING':'TRČI','JUMP':'SKOK','SWORD':'MAČ','DASH':'DASH','BUILD':'GRADI','GEAR':'OPREMA'},
  es:{'FAQ':'PREGUNTAS FRECUENTES','LATEST UPDATE':'ÚLTIMA ACTUALIZACIÓN','OPTIONS':'OPCIONES','SETTINGS & CONTROLS':'AJUSTES Y CONTROLES','EXIT':'SALIR','CLOSE SESSION':'CERRAR SESIÓN','PLAY NOW':'JUGAR','CONTINUE':'CONTINUAR','PRESS ENTER TO BEGIN':'PULSA ENTER PARA EMPEZAR','A ROOFTOP DELIVERY GAME':'UN JUEGO DE ENTREGA POR LOS TEJADOS','OLD QUARTER':'CASCO ANTIGUO','ROOFTOP RELAY':'RELEVO EN LOS TEJADOS','SIGNALS':'SEÑALES','ROTATE SCREEN':'GIRA LA PANTALLA','Landscape gives the clearest view and full controls.':'El modo horizontal ofrece la mejor vista y todos los controles.','RESUME':'CONTINUAR','MISSIONS':'MISIONES','PROGRESS':'PROGRESO','SETTINGS':'AJUSTES','COURIER TERMINAL':'TERMINAL DEL MENSAJERO','KEEP THE':'MANTÉN LA','LINE OPEN.':'LÍNEA ABIERTA.','RESTART BRIEFING':'REINICIAR BRIEFING','ESC CLOSE':'ESC CERRAR','GAMEPLAY / GUIDANCE':'JUEGO / GUÍA','VOICE & AUDIO':'VOZ Y AUDIO','DISPLAY':'PANTALLA','LANGUAGE':'IDIOMA','TUTORIAL':'TUTORIAL','GAME AUDIO':'AUDIO DEL JUEGO','SCREEN SHAKE':'TEMBLOR DE CÁMARA','REDUCED MOTION':'MOVIMIENTO REDUCIDO','ATMOSPHERIC RAIN':'LLUVIA AMBIENTAL','AI VOICE':'VOZ IA','MUSIC':'MÚSICA','SFX':'EFECTOS','GAME LANGUAGE':'IDIOMA DEL JUEGO','Choose your interface language':'Elige el idioma de la interfaz','FULLSCREEN':'PANTALLA COMPLETA','RESET OPTIONS':'RESTABLECER AJUSTES','CONTROLS':'CONTROLES','DELIVERY COMPLETE':'ENTREGA COMPLETADA','LINE':'LÍNEA','RESTORED.':'RESTAURADA.','NEXT RUN':'SIGUIENTE PARTIDA','NEXT MISSION':'SIGUIENTE MISIÓN','RETURN TO BRIEFING':'VOLVER AL INICIO','SIGNAL LOST':'SEÑAL PERDIDA','RUN':'CORRER','INTERRUPTED.':'INTERRUMPIDA.','TRY AGAIN':'INTENTAR DE NUEVO','RANK UP':'SUBIR DE RANGO','ABILITY UNLOCKED':'HABILIDAD DESBLOQUEADA','SESSION CLOSED':'SESIÓN CERRADA','SEE YOU':'HASTA','SOON.':'PRONTO.','RUNNING':'CORRER','JUMP':'SALTAR','SWORD':'ESPADA','DASH':'DASH','BUILD':'CONSTRUIR','GEAR':'EQUIPO'},
  de:{'FAQ':'FAQ','LATEST UPDATE':'LETZTES UPDATE','OPTIONS':'OPTIONEN','SETTINGS & CONTROLS':'EINSTELLUNGEN & STEUERUNG','EXIT':'BEENDEN','CLOSE SESSION':'SITZUNG SCHLIESSEN','PLAY NOW':'SPIELEN','CONTINUE':'FORTSETZEN','PRESS ENTER TO BEGIN':'ENTER ZUM STARTEN','A ROOFTOP DELIVERY GAME':'EIN SPIEL ÜBER DEN DÄCHERN','OLD QUARTER':'ALTES VIERTEL','ROOFTOP RELAY':'DACH-RELAIS','SIGNALS':'SIGNALE','ROTATE SCREEN':'BILDSCHIRM DREHEN','Landscape gives the clearest view and full controls.':'Querformat bietet die beste Sicht und volle Steuerung.','RESUME':'FORTSETZEN','MISSIONS':'MISSIONEN','PROGRESS':'FORTSCHRITT','SETTINGS':'EINSTELLUNGEN','COURIER TERMINAL':'KURIER-TERMINAL','KEEP THE':'HALTE DIE','LINE OPEN.':'LEITUNG OFFEN.','RESTART BRIEFING':'BRIEFING NEUSTARTEN','ESC CLOSE':'ESC SCHLIESSEN','GAMEPLAY / GUIDANCE':'SPIEL / ANLEITUNG','VOICE & AUDIO':'STIMME & AUDIO','DISPLAY':'ANZEIGE','LANGUAGE':'SPRACHE','TUTORIAL':'TUTORIAL','GAME AUDIO':'SPIELAUDIO','SCREEN SHAKE':'KAMERAWACKELN','REDUCED MOTION':'WENIGER BEWEGUNG','ATMOSPHERIC RAIN':'ATMOSPHÄRISCHER REGEN','AI VOICE':'KI-STIMME','MUSIC':'MUSIK','SFX':'SFX','GAME LANGUAGE':'SPIELSPRACHE','Choose your interface language':'Wähle die Sprache der Oberfläche','FULLSCREEN':'VOLLBILD','RESET OPTIONS':'EINSTELLUNGEN ZURÜCKSETZEN','CONTROLS':'STEUERUNG','DELIVERY COMPLETE':'LIEFERUNG ABGESCHLOSSEN','LINE':'LEITUNG','RESTORED.':'WIEDERHERGESTELLT.','NEXT RUN':'NÄCHSTER LAUF','NEXT MISSION':'NÄCHSTE MISSION','RETURN TO BRIEFING':'ZURÜCK ZUM START','SIGNAL LOST':'SIGNAL VERLOREN','RUN':'LAUF','INTERRUPTED.':'UNTERBROCHEN.','TRY AGAIN':'ERNEUT VERSUCHEN','RANK UP':'RANG AUFGESTIEGEN','ABILITY UNLOCKED':'FÄHIGKEIT FREIGESCHALTET','SESSION CLOSED':'SITZUNG GESCHLOSSEN','SEE YOU':'BIS','SOON.':'BALD.','RUNNING':'LAUFEN','JUMP':'SPRINGEN','SWORD':'KLINGE','DASH':'DASH','BUILD':'BAUEN','GEAR':'AUSRÜSTUNG'}
};

const getLang=()=>localStorage.getItem(LANG_KEY)||'en';
const text=key=>T[getLang]?.[key]||T.en[key]||key;
let applying=false;

function translateTextNodes(root=document.body){
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node=>{const raw=node.nodeValue.trim();if(!raw||!T.en[raw])return;node.nodeValue=node.nodeValue.replace(raw,text(raw));});
  document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=text(el.dataset.i18n));
  document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',text(el.dataset.i18nAria)));
}
function applyLanguage(lang=getLang(),emit=true){
  if(!T[lang])lang='en';localStorage.setItem(LANG_KEY,lang);document.documentElement.lang=lang==='exyu'?'bs':lang;translateTextNodes();
  if(emit&&!applying)window.dispatchEvent(new CustomEvent('relay-language-change',{detail:{lang}}));
}
function buildLanguageUI(){
  if(document.getElementById('relayLanguagePanel'))return;
  const panel=document.createElement('section');panel.id='relayLanguagePanel';panel.className='relay-language-panel hidden';
  panel.innerHTML=`<div class="relay-language-card" role="dialog" aria-modal="true"><button type="button" class="relay-language-close" aria-label="Close">×</button><p class="relay-info-eyebrow">RELAY RUNNER</p><h2 data-i18n="LANGUAGE">LANGUAGE</h2><div class="relay-language-list">${Object.entries(LANGUAGES).map(([code,name])=>`<button type="button" data-language="${code}"><span>${name}</span><b>${code.toUpperCase()}</b></button>`).join('')}</div></div>`;
  document.body.appendChild(panel);
  panel.addEventListener('click',e=>{const choice=e.target.closest('[data-language]');if(choice){applyLanguage(choice.dataset.language);panel.classList.add('hidden');}if(e.target===panel||e.target.closest('.relay-language-close'))panel.classList.add('hidden');});
}
window.relayI18n={applyLanguage,getLang,text,languages:LANGUAGES};
window.addEventListener('relay-language-change',e=>{const lang=e.detail?.lang||e.detail?.code;if(!lang||applying)return;applying=true;applyLanguage(lang,false);applying=false;});
const observer=new MutationObserver(mutations=>{if(applying)return;for(const m of mutations){if(m.addedNodes?.length){translateTextNodes();break;}}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{buildLanguageUI();applyLanguage();observer.observe(document.body,{childList:true,subtree:true});},{once:true});
else{buildLanguageUI();applyLanguage();observer.observe(document.body,{childList:true,subtree:true});}
