// Relay Runner — stable viewport synchronization.
//
// Goals:
// - Keep mobile viewport / Phaser / DOM HUD synchronized.
// - Never create a synthetic resize feedback loop.
// - Do not classify desktop DevTools as "mobile" just because the
//   DevTools panel makes the viewport narrower.
// - Keep real phone/tablet rotation support.
//
// Important:
// This module observes browser viewport changes, but synthetic resize
// notifications generated by this module are never allowed to re-enter
// the synchronization pipeline.

'use strict';

const isRealMobileViewport = () => {
  const coarse =
    window.matchMedia?.('(pointer: coarse)')?.matches === true;

  const touchPoints =
    Number(navigator.maxTouchPoints) > 0;

  const mobileUA =
    /Android|iPhone|iPad|iPod|Mobile|Windows Phone|Silk|Kindle/i.test(
      navigator.userAgent || ''
    );

  return coarse || touchPoints || mobileUA;
};

const getViewportSize = () => {
  const vv = window.visualViewport;

  const width = Math.round(
    vv?.width ||
    window.innerWidth ||
    document.documentElement.clientWidth ||
    0
  );

  const height = Math.round(
    vv?.height ||
    window.innerHeight ||
    document.documentElement.clientHeight ||
    0
  );

  return {
    width,
    height
  };
};

const getLayoutSize = () => {
  const play = document.getElementById('play');

  if (!play) {
    return null;
  }

  const rect = play.getBoundingClientRect();

  return {
    width: Math.round(rect.width),
    height: Math.round(rect.height)
  };
};

let settleToken = 0;
let lastApplied = '';
let running = false;
let syntheticResizeDepth = 0;
let scheduled = false;

const waitFrame = () =>
  new Promise(resolve => {
    requestAnimationFrame(resolve);
  });

async function waitForStableViewport(token) {
  let previous = '';
  let stableFrames = 0;

  for (let i = 0; i < 12; i += 1) {
    await waitFrame();

    if (token !== settleToken) {
      return null;
    }

    const viewport = getViewportSize();
    const layout = getLayoutSize();

    const current =
      `${viewport.width}x${viewport.height}` +
      `|${layout?.width || 0}x${layout?.height || 0}`;

    if (current === previous) {
      stableFrames += 1;
    } else {
      stableFrames = 0;
    }

    previous = current;

    if (
      stableFrames >= 2 &&
      viewport.width > 0 &&
      viewport.height > 0
    ) {
      return {
        viewport,
        layout
      };
    }
  }

  if (token !== settleToken) {
    return null;
  }

  return {
    viewport: getViewportSize(),
    layout: getLayoutSize()
  };
}

const dispatchSyntheticResize = () => {
  syntheticResizeDepth += 1;

  try {
    window.dispatchEvent(
      new Event('resize')
    );
  } finally {
    syntheticResizeDepth = Math.max(
      0,
      syntheticResizeDepth - 1
    );
  }
};

async function syncViewport(reason = 'resize') {
  if (!isRealMobileViewport()) {
    return;
  }

  const token = ++settleToken;

  running = true;

  try {
    const settled =
      await waitForStableViewport(token);

    if (
      !settled ||
      token !== settleToken
    ) {
      return;
    }

    const {
      width,
      height
    } = settled.viewport;

    const layout =
      settled.layout;

    const key =
      `${width}x${height}` +
      `|${layout?.width || 0}x${layout?.height || 0}`;

    if (
      key === lastApplied &&
      reason !== 'orientationchange'
    ) {
      return;
    }

    lastApplied = key;

    document.documentElement.style.setProperty(
      '--relay-viewport-width',
      `${width}px`
    );

    document.documentElement.style.setProperty(
      '--relay-viewport-height',
      `${height}px`
    );

    document.documentElement.dataset.relayOrientation =
      width >= height
        ? 'landscape'
        : 'portrait';

    /*
     * Phaser Scale.RESIZE listens for resize.
     *
     * These notifications are deliberately marked so this module's
     * own resize listener ignores them.
     */
    dispatchSyntheticResize();

    await waitFrame();

    if (token !== settleToken) {
      return;
    }

    dispatchSyntheticResize();

    document.dispatchEvent(
      new CustomEvent(
        'relay:viewport-settled',
        {
          detail: {
            reason,
            width,
            height,
            orientation:
              width >= height
                ? 'landscape'
                : 'portrait'
          }
        }
      )
    );
  } finally {
    if (token === settleToken) {
      running = false;
    }
  }
}

const schedule = reason => {
  if (scheduled) {
    return;
  }

  scheduled = true;

  requestAnimationFrame(() => {
    scheduled = false;

    /*
     * Ignore synthetic resize events generated by this module.
     */
    if (syntheticResizeDepth > 0) {
      return;
    }

    syncViewport(reason);
  });
};

window.addEventListener(
  'orientationchange',
  () => {
    schedule('orientationchange');
  },
  {
    passive: true
  }
);

window.addEventListener(
  'resize',
  () => {
    /*
     * A resize generated by this module must never schedule another
     * viewport synchronization pass.
     */
    if (syntheticResizeDepth > 0) {
      return;
    }

    /*
     * While settling, another browser resize supersedes the old pass.
     */
    if (running) {
      settleToken += 1;
      running = false;
    }

    schedule('resize');
  },
  {
    passive: true
  }
);

window.visualViewport?.addEventListener(
  'resize',
  () => {
    schedule('visualViewport.resize');
  },
  {
    passive: true
  }
);

/*
 * Initial pass.
 *
 * Only real mobile/touch environments enter this controller.
 * Desktop + DevTools therefore stays on the normal desktop runtime.
 */
if (document.readyState === 'loading') {
  document.addEventListener(
    'DOMContentLoaded',
    () => {
      if (isRealMobileViewport()) {
        schedule('initial');
      }
    },
    {
      once: true
    }
  );
} else if (isRealMobileViewport()) {
  schedule('initial');
}
