import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const upgrades = await readFile(new URL('../src/upgrades.js', import.meta.url), 'utf8');
const runner = await readFile(new URL('../src/scenes/RunnerScene.js', import.meta.url), 'utf8');
const main = await readFile(new URL('../src/main.js', import.meta.url), 'utf8');
const index = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const styles = await readFile(new URL('../styles.css', import.meta.url), 'utf8');

assert.match(upgrades, /id: 'shield'/, 'Relay Shield must be purchasable');
assert.match(upgrades, /id: 'kinetic-ball'/, 'Kinetic Ball must be purchasable');
assert.match(upgrades, /id: 'turret'/, 'Arc Turret must be purchasable');
assert.match(upgrades, /id: 'spring-pad'/, 'Spring Pad must be purchasable');
assert.match(upgrades, /id: 'pulse-rifle'/, 'Pulse Rifle must be purchasable');
assert.match(upgrades, /id: 'scattergun'/, 'Scattergun must be purchasable');
assert.match(runner, /this\.keys\.ONE.*this\.useBuild\(0\)/, 'Key 1 must deploy build slot one');
assert.match(runner, /this\.keys\.TWO.*this\.useBuild\(1\)/, 'Key 2 must deploy build slot two');
assert.match(runner, /this\.keys\.THREE.*this\.useGadget\(0\)/, 'Key 3 must activate gadget slot one');
assert.match(runner, /this\.keys\.FOUR.*this\.useGadget\(1\)/, 'Key 4 must activate gadget slot two');
assert.match(runner, /this\.keys\.E\)\) this\.useBlaster\(\)/, 'E must fire the spawn blaster');
assert.match(runner, /Phaser\.Input\.Keyboard\.JustDown\(this\.keys\.Q\)/, 'Q must activate the always-available sword');
assert.match(index, /data-mobile-action="sword"/, 'Touch controls must include a sword button');
assert.match(index, /data-mobile-action="dash"/, 'Touch controls must include a nitro button');
assert.match(index, /data-mobile-action="build1"/, 'Touch controls must include build slot one');
assert.match(index, /data-mobile-action="gadget1"/, 'Touch controls must include gadget slot one');
assert.match(index, /data-mobile-action="jump"/, 'Touch controls must include a jump button');
assert.match(index, /data-mobile-joystick/, 'Touch controls must include a drag joystick for movement');
assert.match(index, /mobile-joystick-thumb/, 'The joystick must render a draggable thumb element');
assert.match(main, /game\.events\.emit\('mobile-action'/, 'Touch controls must send gameplay actions');
assert.match(main, /function speakNarration\(text\)/, 'English browser narration must be available for cinematic subtitles');
assert.match(main, /claimLoginReward/, 'The challenge board must provide persistent login rewards');
assert.match(main, /WEEKLY/, 'The challenge board must explain and display weekly missions');
assert.match(main, /const joystick = document\.querySelector\('\[data-mobile-joystick\]'\)/, 'App must wire up the joystick drag element');
assert.match(main, /game\.events\.emit\('mobile-move', direction\)/, 'The joystick must send movement directions while dragging');
assert.match(main, /setDirection\(null\)/, 'The joystick must clear movement direction on release');
assert.match(runner, /this\.mobileActions\.sword/, 'The runner must consume the mobile sword action');
assert.match(runner, /this\.mobileActions\.dash/, 'The runner must consume the mobile nitro action');
assert.match(runner, /this\.mobileActions\.build1/, 'The runner must consume mobile build actions');
assert.match(runner, /this\.mobileActions\.gadget1/, 'The runner must consume mobile gadget actions');
assert.match(runner, /this\.mobileDirection === 'left'/, 'The runner must consume touch movement directions');
assert.match(runner, /this\.mobileActions\.jump/, 'The runner must consume the touch jump action');
assert.match(styles, /body #pauseMenu \.menu-grid\{grid-template-columns:1fr/, 'Pause settings must collapse to one column on touch screens');
assert.match(styles, /body\.is-touch \.mobile-joystick\{/, 'Joystick styling must be scoped to detected touch devices');
assert.match(main, /const detectTouchDevice = \(\) => \{/, 'App must detect touch capability using multiple redundant signals');
assert.match(main, /hasTouchPoints \|\| hasTouchEvents \|\| coarsePointer \|\| mobileUA/, 'Touch detection must avoid showing touch controls on desktop based only on viewport size');
assert.match(main, /document\.body\.classList\.toggle\('is-touch', detectTouchDevice\(\)\)/, 'App must apply the detected state as a body class driving all touch CSS');
assert.match(styles, /^body\.is-touch \.mobile-controls\{--touch-size:clamp\(46px,13vw,60px\);position:absolute;z-index:30;left:max\(/m, 'Touch controls must be visible with scalable, safe-area-aware positioning');
assert.doesNotMatch(styles, /hover:hover\) and \(pointer:fine\)/, 'Touch control visibility must not depend on unreliable hover/pointer media features');
assert.match(index, /class="rotate-prompt"/, 'The play screen must include a rotate-to-landscape prompt');
assert.match(index, /data-rotate-dismiss/, 'The rotate prompt must be dismissible');
assert.match(main, /data-rotate-dismiss.*rotate-dismissed/, 'Dismissing the rotate prompt must persist for the current orientation session');
assert.match(styles, /@media \(orientation:portrait\)\{body\.is-touch:not\(\.rotate-dismissed\) \.rotate-prompt\{/, 'The rotate prompt must show in portrait whenever the touch class is applied');
assert.match(styles, /@supports \(padding:max\(0px\)\)\{body\.is-touch \.mobile-controls\{bottom:max\(/, 'Touch controls must progressively enhance safe-area spacing only when supported');
assert.match(styles, /@media \(max-height:480px\) and \(orientation:landscape\)/, 'Touch controls must adapt for short landscape screens');
assert.match(styles, /@media \(min-width:600px\)\{body\.is-touch \.mobile-controls button\{width:74px/, 'Touch controls must size up on tablets and larger screens');
assert.match(runner, /defeatEnemy\(enemy, 'STOMP'\)/, 'Enemies must be stompable');
assert.match(runner, /BLOCKS THE RELAY · DEFEAT IT/, 'Configured bosses must gate completion');
assert.match(runner, /this\.mission\.boss/, 'Boss encounters must be mission-defined');
assert.match(runner, /gravityMode === 'low'/, 'Galaxy routes must support low gravity');
assert.match(runner, /createOpeningCinematic/, 'The first route must provide the arrival cinematic');
assert.match(runner, /EARTH ORBIT · RELAY DISTRESS SIGNAL RECEIVED/, 'The opening cinematic must establish the Earth departure');
assert.match(runner, /this\.game\.events\.emit\('narration'/, 'The opening cinematic must emit narrated subtitle beats');
assert.match(runner, /updateWeather\(delta\)/, 'Routes must update dynamic weather fronts');
assert.match(runner, /FRONT ACTIVE/, 'Weather fronts must communicate their active state');
assert.match(runner, /FIRES ONLY WHEN CLOSE/, 'The introductory threat must teach its proximity firing rule');
assert.match(runner, /const firingRange =/, 'Hostile shots must be explicitly range-gated');
assert.match(runner, /const backdrop =/, 'Every route must select a distinct backdrop treatment');
assert.match(runner, /createGuideCompanions/, 'Routes must provide friendly guide companions');
assert.match(runner, /TAP \/ CLICK \/ ESC TO DISMISS/, 'Tutorial information cards must be manually dismissible');
assert.match(runner, /const width = this\.scale\.width/, 'The tutorial cinematic must size itself to the active canvas');
assert.match(runner, /const panelWidth = compact \? Math\.min\(width - 32, 420\) : width - 44/, 'The tutorial must use a full-width desktop panel and a capped mobile card');
assert.match(runner, /compact \? 3600 : 5600/, 'The mobile tutorial card must auto-close sooner');
assert.match(runner, /RELAY \/\/ ORIENTATION/, 'The tutorial cinematic must provide an orientation label');
assert.match(runner, /A \/ D  MOVE/, 'The tutorial cinematic must show the core control prompt');
assert.match(runner, /FOLLOW THE GOLD SIGNALS/, 'The tutorial cinematic must explain route guidance');
assert.match(runner, /CHECKPOINTS SAVE YOUR RUN/, 'The tutorial cinematic must explain recovery guidance');
assert.match(runner, /firstTimeTutorial/, 'Tutorial presentation must support first-time-only onboarding');
assert.match(runner, /createMissionTransmission/, 'Later routes must provide progression transmissions');
assert.match(runner, /ammoMax = 6/, 'Blaster must have a defined plasma capacity');
assert.match(runner, /updateBuilds\(\)/, 'Turrets and builds must update at runtime');
assert.match(main, /ownedBuildItems/, 'Build item ownership must persist in application state');
assert.match(main, /replayTutorial/, 'Settings must expose tutorial replay');
assert.match(main, /game\.events\.on\('sector'/, 'Extended routes must announce sector two in the HUD');
assert.match(main, /missionUnlocked\(index\)/, 'Launch flow must enforce mission unlock requirements');
assert.match(main, /contractTab\.dataset\.tab = 'contracts'/, 'Dynamic pause tabs must have tab identifiers');
assert.match(main, /if \(tab === 'contracts'\) renderContracts\(\)/, 'Dynamic contracts tab must render through the shared tab system');
assert.match(main, /activeContract: selectedJob\.contract \|\| null/, 'Contracts must be scoped to the prepared run');
assert.match(runner, /setCollideWorldBounds\(true\)/, 'Player must stay within configured world bounds');
assert.match(runner, /this\.worldWidth \+ 50/, 'Extended routes must retain sector-two projectiles');
assert.match(main, /hud-vital energy/, 'HUD must include an Energy telemetry module');
assert.match(main, /hud-vital health/, 'HUD must include a Health telemetry module');
assert.match(main, /hud-vital plasma/, 'HUD must include a Plasma telemetry module');
assert.match(runner, /safeCheckpointSpawn\(x\)/, 'Checkpoint recovery must find a safe platform spawn');
assert.match(runner, /platform\.y - 46/, 'Checkpoint recovery must place the runner above a platform');
assert.match(runner, /respawnGrace = 1100/, 'Checkpoint recovery must give the runner a brief safety window');
for (const id of ['nextMission', 'closeLevelUp', 'closeAbilityUnlock', 'signalTotal', 'signalProgress', 'runScore', 'runTime', 'progressValue', 'missionNumber']) {
  assert.match(index, new RegExp(`id="${id}"`), `Runtime element #${id} must exist in the initial markup`);
}
assert.match(main, /id="worldMap"/, 'World Map markup must be created by the runtime');
assert.match(main, /id="preflight"/, 'Preflight markup must be created by the runtime');
assert.doesNotMatch(index, /id="worldMap"|id="preflight"/, 'World Map and Preflight IDs must not be duplicated in static markup');
assert.doesNotMatch(main, /renderProfile|applyHudStyle|hudTheme|hudAccent/, 'Removed HUD/Profile customizers must not remain active');

console.log('Build system control and shop coverage checks passed.');
