import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const upgrades = await readFile(new URL('../src/upgrades.js', import.meta.url), 'utf8');
const runner = await readFile(new URL('../src/scenes/RunnerScene.js', import.meta.url), 'utf8');
const main = await readFile(new URL('../src/main.js', import.meta.url), 'utf8');
const index = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const styles = await readFile(new URL('../styles.css', import.meta.url), 'utf8');
const mobileOwner = await readFile(new URL('../src/systems/mobile-input-single-owner-v1.js', import.meta.url), 'utf8');

assert.match(upgrades, /id: 'shield'/, 'Relay Shield must be purchasable');
assert.match(upgrades, /id: 'kinetic-ball'/, 'Kinetic Ball must be purchasable');
assert.match(upgrades, /id: 'turret'/, 'Arc Turret must be purchasable');
assert.match(upgrades, /id: 'spring-pad'/, 'Spring Pad must be purchasable');
assert.match(upgrades, /id: 'pulse-rifle'/, 'Pulse Rifle must be purchasable');
assert.match(upgrades, /id: 'scattergun'/, 'Scattergun must be purchasable');
assert.match(runner, /this\.keys\.ONE/, 'Key 1 must be wired');
assert.match(runner, /this\.useBuild\(0\)/, 'Key 1 must deploy build slot one');
assert.match(runner, /this\.keys\.TWO/, 'Key 2 must be wired');
assert.match(runner, /this\.useBuild\(1\)/, 'Key 2 must deploy build slot two');
assert.match(runner, /this\.keys\.THREE/, 'Key 3 must be wired');
assert.match(runner, /this\.useGadget\(0\)/, 'Key 3 must activate gadget slot one');
assert.match(runner, /this\.keys\.FOUR/, 'Key 4 must be wired');
assert.match(runner, /this\.useGadget\(1\)/, 'Key 4 must activate gadget slot two');
assert.match(runner, /this\.keys\.E[\s\S]{0,160}?this\.useBlaster\(\)/, 'E must fire the spawn blaster');
assert.match(runner, /Phaser\.Input\.Keyboard\.JustDown\(\s*this\.keys\.Q\s*\)/, 'Q must activate the always-available sword');
assert.match(index, /data-mobile-action="sword"/, 'Touch controls must include a sword button');
assert.match(index, /data-mobile-action="dash"/, 'Touch controls must include a nitro button');
assert.match(index, /data-mobile-action="build1"/, 'Touch controls must include build slot one');
assert.match(index, /data-mobile-action="gadget1"/, 'Touch controls must include gadget slot one');
assert.match(index, /data-mobile-action="jump"/, 'Touch controls must include a jump button');
assert.match(index, /data-mobile-joystick/, 'Touch controls must include a drag joystick for movement');
assert.match(index, /mobile-joystick-thumb/, 'The joystick must render a draggable thumb element');
assert.match(mobileOwner, /ACTION_KEYS/, 'Single mobile owner must define gameplay action bindings');
assert.match(mobileOwner, /emit\(ACTION_KEYS\[action\], 'keydown'\)/, 'Single mobile owner must send gameplay action keydown events');
assert.match(mobileOwner, /emit\(ACTION_KEYS\[action\], 'keyup'\)/, 'Single mobile owner must send gameplay action keyup events');
assert.match(mobileOwner, /window\.dispatchEvent\(keyEvent/, 'Single mobile owner must dispatch synthetic gameplay keyboard events');
assert.match(main, /function speakNarration\(text\)/, 'English browser narration must be available for cinematic subtitles');
assert.match(main, /claimLoginReward/, 'The challenge board must provide persistent login rewards');
assert.match(main, /WEEKLY/, 'The challenge board must explain and display weekly missions');
assert.match(mobileOwner, /const joystickNode = root\.querySelector\('\[data-mobile-joystick\]'\)/, 'Single mobile owner must wire the joystick drag element');
assert.match(mobileOwner, /mobile-move|setPhaserDirection/, 'Single mobile owner must route joystick movement');
assert.match(mobileOwner, /setDirection\(null\)/, 'Single mobile owner must clear movement direction on release');
assert.doesNotMatch(main, /data-mobile-joystick|mobile-move|activePointerId/, 'main.js must not own mobile joystick dispatch');
assert.match(runner, /this\.mobileActions\.sword/, 'The runner must consume the mobile sword action');
assert.match(runner, /this\.mobileActions\.dash/, 'The runner must consume the mobile nitro action');
assert.match(runner, /this\.mobileActions\.build1/, 'The runner must consume mobile build actions');
assert.match(runner, /this\.mobileActions\.gadget1/, 'The runner must consume mobile gadget actions');
assert.match(runner, /this\.mobileDirection === 'left'/, 'The runner must consume touch movement directions');
assert.match(runner, /this\.mobileActions\.jump/, 'The runner must consume the touch jump action');
assert.match(styles, /body #pauseMenu \.menu-grid\{grid-template-columns:1fr/, 'Pause settings must collapse to one column on touch screens');
assert.match(styles, /body\.is-touch \.mobile-joystick\{/, 'Joystick styling must be scoped to detected touch devices');
assert.match(main, /const detectTouchDevice = \(\) => \{/, 'App must detect touch capability using multiple redundant signals');
assert.match(main, /hasTouchPoints \|\| hasTouchEvents \|\| coarsePointer \|\| mobileUA/, 'Touch detection must avoid showing touch controls on desktop based only on viewport size');
assert.match(main, /document\.body\.classList\.toggle\('is-touch', detectTouchDevice\(\)\)/, 'App must apply the detected state as a body class driving all touch CSS');